<?php
namespace Box\TestScribe\_fixture\_input;

/**
 * Generated by TestScribe.
 */
class ExceptionInstanceGenTest extends \Box\TestScribe\_fixture\TestCase
{
    /**
     * @covers \Box\TestScribe\_fixture\_input\ExceptionInstance::throwExceptionWhenTheInputIsNotPositive
     * @covers \Box\TestScribe\_fixture\_input\ExceptionInstance
     */
    public function test_throwExceptionWhenTheInputIsNotPositive()
    {
        $this->setExpectedException('InvalidArgumentException', 'Input should be a positive number');

        // Execute the method under test.

        $objectUnderTest = new \Box\TestScribe\_fixture\_input\ExceptionInstance();

        $objectUnderTest->throwExceptionWhenTheInputIsNotPositive(-1);
    }
}
