<?php
namespace Box\TestScribe\_fixture\_input;

/**
 * Generated by PHPUnit_test_Generator.
 */
class ExceptionInstanceGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\_fixture\_input\ExceptionInstance::throwException
     * @covers \Box\TestScribe\_fixture\_input\ExceptionInstance
     */
    public function testThrowException()
    {
        $this->setExpectedException('InvalidArgumentException');

        // Execute the method under test.

        $objectUnderTest = new \Box\TestScribe\_fixture\_input\ExceptionInstance();

        $objectUnderTest->throwException();
    }
}
