<?php
namespace Box\TestScribe\_fixture\_input;

/**
 * Generated by TestScribe.
 */
class ExceptionInstanceGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\_fixture\_input\ExceptionInstance::throwExceptionWhenTheInputIsNotPositive
     * @covers \Box\TestScribe\_fixture\_input\ExceptionInstance
     */
    public function test_throwExceptionWhenTheInputIsNotPositive()
    {
        $this->setExpectedException('InvalidArgumentException');

        // Execute the method under test.

        $objectUnderTest = new \Box\TestScribe\_fixture\_input\ExceptionInstance();

        $objectUnderTest->throwExceptionWhenTheInputIsNotPositive(-1);
    }
}
