<?php
namespace Box\TestScribe\_fixture\_input;

/**
 * Generated by PHPUnit_test_Generator.
 */
class SideEffectExampleGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\_fixture\_input\SideEffectExample::methodThatHasSideEffect
     * @covers \Box\TestScribe\_fixture\_input\SideEffectExample
     */
    public function testMethodThatHasSideEffect()
    {
        // Setup mocks for parameters to the method under test.

        /** @var \Box\TestScribe\_fixture\_input\Logger $mockLogger1 */
        $mockLogger1 = $this->shmock(
            '\\Box\\TestScribe\\_fixture\\_input\\Logger',
            function (
                /** @var \Box\TestScribe\_fixture\_input\Logger|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                $shmock->log('methodThatHasSideEffect is called.');
            }
        );

        // Execute the method under test.

        $objectUnderTest = new \Box\TestScribe\_fixture\_input\SideEffectExample();

        $objectUnderTest->methodThatHasSideEffect($mockLogger1);
    }
}
