<?php
namespace Box\TestScribe\ClassInfo;

/**
 * Generated by TestScribe.
 */
class ClassUtilGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\ClassInfo\ClassUtil::getMethodNames
     * @covers \Box\TestScribe\ClassInfo\ClassUtil
     */
    public function test_getMethodNames()
    {
        // Execute the method under test.

        $objectUnderTest = new \Box\TestScribe\ClassInfo\ClassUtil();

        $executionResult = $objectUnderTest->getMethodNames('\Box\TestScribe\ClassInfo\ClassUtil');

        // Validate the execution result.

        $this->assertInternalType('array', $executionResult);
        $this->assertCount(1, $executionResult);
        $expected = 'getMethodNames';
        $this->assertSame(
            $expected,
            $executionResult[0],
            'Variable ( executionResult[0] ) doesn\'t have the expected value.'
        );
    }
}
