<?php
namespace Box\TestScribe\Mock;

/**
 * Generated by TestScribe.
 */
class MockObjectNameMgrGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\Mock\MockObjectNameMgr::getMockObjectName
     * @covers \Box\TestScribe\Mock\MockObjectNameMgr
     */
    public function test_getMockObjectName()
    {
        // Execute the method under test.

        $objectUnderTest = new \Box\TestScribe\Mock\MockObjectNameMgr();

        $executionResult = $objectUnderTest->getMockObjectName('ClassName');

        // Validate the execution result.

        $expected = 'mockClassName';
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }
}
