<?php
namespace Box\TestScribe\Utils;

/**
 * Generated by PHPUnit_test_Generator.
 */
class StringUtilGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;
    
    /**
     * @covers Box\TestScribe\Utils\StringUtil::isStringStartWith
     */
    public function testIsStringStartWithNotPrefix()
    {
        $executionResult = \Box\TestScribe\Utils\StringUtil::isStringStartWith('subject', 'none');
        $expected = false;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }


    /**
     * @covers Box\TestScribe\Utils\StringUtil::isStringStartWith
     */
    public function testIsStringStartWithCaseMismatch()
    {
        $executionResult = \Box\TestScribe\Utils\StringUtil::isStringStartWith('subject', 'Su');
        $expected = false;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }

    /**
     * @covers Box\TestScribe\Utils\StringUtil::isStringStartWith
     */
    public function testIsStringStartWithMatch()
    {

        // Execute the method under test.

        $executionResult = \Box\TestScribe\Utils\StringUtil::isStringStartWith('subject', 'su');

        // Validate the execution result.

        $expected = true;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }

}
