<?php
namespace Box\TestScribe\Config;

/**
 * Generated by TestScribe.
 */
class OutputConfigGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\Config\OutputConfig::getOutputParams
     * @covers \Box\TestScribe\Config\OutputConfig
     */
    public function test_getOutputParams()
    {
        // Setup mocks for parameters to the method under test.

        /** @var \Box\TestScribe\Config\Options $mockOptions */
        $mockOptions = $this->shmock(
            '\\Box\\TestScribe\\Config\\Options',
            function (
                /** @var \Box\TestScribe\Config\Options|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->getOutSourceFileDir();
                $mock->return_value('out_source');

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->isOverwriteExistingDestinationFile();
                $mock->return_value(true);
            }
        );

        /** @var \Box\TestScribe\Config\ConfigParams $mockConfigParams */
        $mockConfigParams = $this->shmock(
            '\\Box\\TestScribe\\Config\\ConfigParams',
            function (
                /** @var \Box\TestScribe\Config\ConfigParams|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->getFullClassName();
                $mock->return_value('\\input\\class');

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->getMethodName();
                $mock->return_value('in_method');
            }
        );

        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Config\OutputTestNameGetter $mockOutputTestNameGetter */
        $mockOutputTestNameGetter = $this->shmock(
            '\\Box\\TestScribe\\Config\\OutputTestNameGetter',
            function (
                /** @var \Box\TestScribe\Config\OutputTestNameGetter|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->getTestName();
                $mock->return_value('out_method');
            }
        );

        /** @var \Box\TestScribe\Spec\SavedSpecs $mockSavedSpecs */
        $mockSavedSpecs = $this->shmock(
            '\\Box\\TestScribe\\Spec\\SavedSpecs',
            function (
                /** @var \Box\TestScribe\Spec\SavedSpecs|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                // Set up mocks of return values.

                /** @var \Box\TestScribe\Spec\SpecsPerClass $mockSpecsPerClass */
                $mockSpecsPerClass = $this->shmock(
                    '\\Box\\TestScribe\\Spec\\SpecsPerClass',
                    function (
                        /** @var \Box\TestScribe\Spec\SpecsPerClass|\Shmock\PHPUnitMockInstance $shmock */
                        $shmock
                    ) {
                        $shmock->order_matters();
                        $shmock->disable_original_constructor();
                    }
                );

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->loadExistingSpecs();
                $mock->return_value($mockSpecsPerClass);
            }
        );

        $objectUnderTest = new \Box\TestScribe\Config\OutputConfig($mockOutputTestNameGetter, $mockSavedSpecs);

        $executionResult = $objectUnderTest->getOutputParams($mockOptions, $mockConfigParams);

        // Validate the execution result.

        $this->assertInstanceOf(
            'Box\\TestScribe\\Config\\ConfigParams',
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected type.'
        );

        $this->assertSame(
            '{"file path":"out_source\\/classGenTest.php","class name":"\\\\input\\\\classGenTest","method name":"out_method"}',
            json_encode($executionResult),
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );

    }
}
