<?php
namespace Box\TestScribe\Config;

/**
 * Generated by PHPUnit_test_Generator.
 */
class PathUtilGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\Config\PathUtil::getPathUnderRoot
     * @covers \Box\TestScribe\Config\PathUtil
     */
    public function test_getPathUnderRoot()
    {
        // Execute the method under test.

        $executionResult = \Box\TestScribe\Config\PathUtil::getPathUnderRoot('root', '/relative/to/root');

        // Validate the execution result.

        $expected = 'root/relative/to/root';
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }

    /**
     * @covers \Box\TestScribe\Config\PathUtil::getPathUnderRoot
     * @covers \Box\TestScribe\Config\PathUtil
     */
    public function test_getPathUnderRoot_empty_relative_path()
    {
        // Execute the method under test.

        $executionResult = \Box\TestScribe\Config\PathUtil::getPathUnderRoot('root', '');

        // Validate the execution result.

        $expected = 'root';
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }
}
