<?php
namespace Box\TestScribe\Renderers;

/**
 * Generated by TestScribe.
 */
class ExceptionRendererGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\Renderers\ExceptionRenderer::genExceptionExpectation
     * @covers \Box\TestScribe\Renderers\ExceptionRenderer
     */
    public function test_genExceptionExpectation()
    {
        // Setup mocks for parameters to the method under test.

        /** @var \Box\TestScribe\Execution\ExecutionResult $mockExecutionResult */
        $mockExecutionResult = $this->shmock(
            '\\Box\\TestScribe\\Execution\\ExecutionResult',
            function (
                /** @var \Box\TestScribe\Execution\ExecutionResult|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->getException();
                $mock->return_value(null);
            }
        );

        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Utils\VarExporter $mockVarExporter */
        $mockVarExporter = $this->shmock(
            '\\Box\\TestScribe\\Utils\\VarExporter',
            function (
                /** @var \Box\TestScribe\Utils\VarExporter|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();
            }
        );

        $objectUnderTest = new \Box\TestScribe\Renderers\ExceptionRenderer($mockVarExporter);

        $executionResult = $objectUnderTest->genExceptionExpectation($mockExecutionResult);

        // Validate the execution result.

        $expected = '';
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }
}
