<?php
namespace Box\TestScribe\Examples\CombinatorialExplosion;

/**
 * Generated by TestScribe.
 */
class UnitTestApproachGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach::isAllTrue
     * @covers \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach
     */
    public function test_isAllTrue_1()
    {
        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Examples\CombinatorialExplosion\BothTrueLevel2 $mockBothTrueLevel2 */
        $mockBothTrueLevel2 = $this->shmock(
            '\\Box\\TestScribe\\Examples\\CombinatorialExplosion\\BothTrueLevel2',
            function (
                /** @var \Box\TestScribe\Examples\CombinatorialExplosion\BothTrueLevel2|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->f2(true, false, true, false);
                $mock->return_value(false);

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->f2(true, false, true, false);
                $mock->return_value(false);
            }
        );

        $objectUnderTest = new \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach($mockBothTrueLevel2);

        $executionResult = $objectUnderTest->isAllTrue(true, false, true, false, true, false, true, false);

        // Validate the execution result.

        $expected = false;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }

    /**
     * @covers \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach::isAllTrue
     * @covers \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach
     */
    public function test_isAllTrue_2()
    {
        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Examples\CombinatorialExplosion\BothTrueLevel2 $mockBothTrueLevel2 */
        $mockBothTrueLevel2 = $this->shmock(
            '\\Box\\TestScribe\\Examples\\CombinatorialExplosion\\BothTrueLevel2',
            function (
                /** @var \Box\TestScribe\Examples\CombinatorialExplosion\BothTrueLevel2|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->f2(true, false, true, false);
                $mock->return_value(false);

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->f2(true, false, true, false);
                $mock->return_value(true);
            }
        );

        $objectUnderTest = new \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach($mockBothTrueLevel2);

        $executionResult = $objectUnderTest->isAllTrue(true, false, true, false, true, false, true, false);

        // Validate the execution result.

        $expected = false;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }

    /**
     * @covers \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach::isAllTrue
     * @covers \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach
     */
    public function test_isAllTrue_3()
    {
        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Examples\CombinatorialExplosion\BothTrueLevel2 $mockBothTrueLevel2 */
        $mockBothTrueLevel2 = $this->shmock(
            '\\Box\\TestScribe\\Examples\\CombinatorialExplosion\\BothTrueLevel2',
            function (
                /** @var \Box\TestScribe\Examples\CombinatorialExplosion\BothTrueLevel2|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->f2(true, false, true, false);
                $mock->return_value(true);

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->f2(true, false, true, false);
                $mock->return_value(false);
            }
        );

        $objectUnderTest = new \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach($mockBothTrueLevel2);

        $executionResult = $objectUnderTest->isAllTrue(true, false, true, false, true, false, true, false);

        // Validate the execution result.

        $expected = false;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }

    /**
     * @covers \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach::isAllTrue
     * @covers \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach
     */
    public function test_isAllTrue_4()
    {
        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Examples\CombinatorialExplosion\BothTrueLevel2 $mockBothTrueLevel2 */
        $mockBothTrueLevel2 = $this->shmock(
            '\\Box\\TestScribe\\Examples\\CombinatorialExplosion\\BothTrueLevel2',
            function (
                /** @var \Box\TestScribe\Examples\CombinatorialExplosion\BothTrueLevel2|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->f2(true, false, true, false);
                $mock->return_value(true);

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->f2(true, false, true, false);
                $mock->return_value(true);
            }
        );

        $objectUnderTest = new \Box\TestScribe\Examples\CombinatorialExplosion\UnitTestApproach($mockBothTrueLevel2);

        $executionResult = $objectUnderTest->isAllTrue(true, false, true, false, true, false, true, false);

        // Validate the execution result.

        $expected = true;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }
}
