<?php
namespace Box\TestScribe;

/**
 * Generated by PHPUnit_test_Generator.
 */
class ClassValueGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers Box\TestScribe\ClassValue::getFullClassName
     */
    public function testGetFullClassName()
    {

        // Execute the method under test.

        $objectUnderTest = new \Box\TestScribe\ClassValue('\namespace\className');
        $executionResult = $objectUnderTest->getFullClassName();

        // Validate the execution result.

        $expected = '\\namespace\\className';
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }
}
