<?php
namespace Box\TestScribe;

/**
 * Generated by PHPUnit_test_Generator.
 */
class GlobalCounterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Box\TestScribe\GlobalCounter::getNextCounter
     */
    public function testGetNextCounter_2nd_counter()
    {

        // Execute the method under test.

        $objectUnderTest = new \Box\TestScribe\GlobalCounter();
        $objectUnderTest->getNextCounter();
        $executionResult = $objectUnderTest->getNextCounter();

        // Validate the execution result.

        $expected = 1;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }
}
