<?php
namespace Box\TestScribe;

/**
 * Generated by TestScribe.
 */
class GlobalFunctionTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers Box\TestScribe\FunctionWrappers\GlobalFunction::__call
     */
    public function testCallGlobalFunctions()
    {

        // Execute the method under test.

        $objectUnderTest = new FunctionWrappers\GlobalFunction();
        $executionResult = $objectUnderTest->__call('file_exists', [__FILE__]);

        // Validate the execution result.

        $expected = true;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );

        $executionResult = $objectUnderTest->__call('file_exists', ['donNotExist.txt']);

        // Validate the execution result.

        $expected = false;
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }
}
