<?php
namespace Box\TestScribe\Input;

/**
 * Generated by TestScribe.
 */
class InputHelperGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\Input\InputHelper::getInputString
     * @covers \Box\TestScribe\Input\InputHelper
     */
    public function test_getInputString()
    {
        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Input\RawInputWithPrompt $mockRawInputWithPrompt1 */
        $mockRawInputWithPrompt1 = $this->shmock(
            '\\Box\\TestScribe\\Input\\RawInputWithPrompt',
            function (
                /** @var \Box\TestScribe\Input\RawInputWithPrompt|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->getString();
                $mock->return_value('h');

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->getString();
                $mock->return_value('foo');
            }
        );

        /** @var \Box\TestScribe\Output $mockOutput2 */
        $mockOutput2 = $this->shmock(
            '\\Box\\TestScribe\\Output',
            function (
                /** @var \Box\TestScribe\Output|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                $shmock->writeln('msg');

                $shmock->writeln('-------------------------------------------------------------' . "\n" .
                'Input help:' . "\n" .
                '' . "\n" .
                '+++ Value input:' . "\n" .
                '' . "\n" .
                'Specify the input in PHP format.' . "\n" .
                '' . "\n" .
                'Use fully qualified class names in place of object variables.' . "\n" .
                'They will be mocked automatically.' . "\n" .
                '' . "\n" .
                'Use the word void to select the default value for a parameter,' . "\n" .
                'or a void return value.' . "\n" .
                '' . "\n" .
                'e.g.' . "\n" .
                '' . "\n" .
                '"ab", \'a\', "a\\n"' . "\n" .
                'true, false, 1, null,' . "\n" .
                '["a", "b"], ["a" => 2], ["a" => ["b" => [ 1, 2]]]' . "\n" .
                '\\ClassFoo , \\Namespace1\\ClassBar' . "\n" .
                '[\\ClassFoo, \\ClassBar]' . "\n" .
                '[\'key\' => \\ClassFoo]' . "\n" .
                'void' . "\n" .
                '' . "\n" .
                '' . "\n" .
                '+++ Other commands:' . "\n" .
                '' . "\n" .
                'a : abort this test generation run.' . "\n" .
                '' . "\n" .
                'End of help' . "\n" .
                '=============================================================');
            }
        );

        $objectUnderTest = new \Box\TestScribe\Input\InputHelper($mockRawInputWithPrompt1, $mockOutput2);

        $executionResult = $objectUnderTest->getInputString('msg');

        // Validate the execution result.

        $expected = 'foo';
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }
}
