<?php
namespace Box\TestScribe\Input;

/**
 * Generated by TestScribe.
 */
class TestNameSelectorGenTest extends \PHPUnit_Framework_TestCase
{
    use \Shmock\Shmockers;

    /**
     * @covers \Box\TestScribe\Input\TestNameSelector::selectTestName
     * @covers \Box\TestScribe\Input\TestNameSelector
     */
    public function test_no_existing()
    {
        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Input\RawInputWithPrompt $mockRawInputWithPrompt */
        $mockRawInputWithPrompt = $this->shmock(
            '\\Box\\TestScribe\\Input\\RawInputWithPrompt',
            function (
                /** @var \Box\TestScribe\Input\RawInputWithPrompt|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();
            }
        );

        /** @var \Box\TestScribe\Output $mockOutput */
        $mockOutput = $this->shmock(
            '\\Box\\TestScribe\\Output',
            function (
                /** @var \Box\TestScribe\Output|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();
            }
        );

        $objectUnderTest = new \Box\TestScribe\Input\TestNameSelector($mockRawInputWithPrompt, $mockOutput);

        $executionResult = $objectUnderTest->selectTestName([]);

        // Validate the execution result.

        $expected = '';
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }

    /**
     * @covers \Box\TestScribe\Input\TestNameSelector::selectTestName
     * @covers \Box\TestScribe\Input\TestNameSelector
     */
    public function test_select_from_existing_tests()
    {
        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Input\RawInputWithPrompt $mockRawInputWithPrompt */
        $mockRawInputWithPrompt = $this->shmock(
            '\\Box\\TestScribe\\Input\\RawInputWithPrompt',
            function (
                /** @var \Box\TestScribe\Input\RawInputWithPrompt|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->getString();
                $mock->return_value('1');
            }
        );

        /** @var \Box\TestScribe\Output $mockOutput */
        $mockOutput = $this->shmock(
            '\\Box\\TestScribe\\Output',
            function (
                /** @var \Box\TestScribe\Output|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                $shmock->writeln('Please select an action by typing the associated number in the following menu.');

                $shmock->writeln('0 : Add a new test.');

                $shmock->writeln('1 : Update test ( t1 ).');

                $shmock->writeln('2 : Update test ( t2 ).');
            }
        );

        $objectUnderTest = new \Box\TestScribe\Input\TestNameSelector($mockRawInputWithPrompt, $mockOutput);

        $executionResult = $objectUnderTest->selectTestName(['t1', 't2']);

        // Validate the execution result.

        $expected = 't1';
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }

    /**
     * @covers \Box\TestScribe\Input\TestNameSelector::selectTestName
     * @covers \Box\TestScribe\Input\TestNameSelector
     */
    public function test_add_new_tests_existing()
    {
        // Execute the method under test.

        // Setup mocks for parameters to the constructor.

        /** @var \Box\TestScribe\Input\RawInputWithPrompt $mockRawInputWithPrompt */
        $mockRawInputWithPrompt = $this->shmock(
            '\\Box\\TestScribe\\Input\\RawInputWithPrompt',
            function (
                /** @var \Box\TestScribe\Input\RawInputWithPrompt|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                /** @var $mock \Shmock\Spec */
                $mock = $shmock->getString();
                $mock->return_value('0');
            }
        );

        /** @var \Box\TestScribe\Output $mockOutput */
        $mockOutput = $this->shmock(
            '\\Box\\TestScribe\\Output',
            function (
                /** @var \Box\TestScribe\Output|\Shmock\PHPUnitMockInstance $shmock */
                $shmock
            ) {
                $shmock->order_matters();
                $shmock->disable_original_constructor();

                $shmock->writeln('Please select an action by typing the associated number in the following menu.');

                $shmock->writeln('0 : Add a new test.');

                $shmock->writeln('1 : Update test ( t1 ).');

                $shmock->writeln('2 : Update test ( t2 ).');
            }
        );

        $objectUnderTest = new \Box\TestScribe\Input\TestNameSelector($mockRawInputWithPrompt, $mockOutput);

        $executionResult = $objectUnderTest->selectTestName(['t1', 't2']);

        // Validate the execution result.

        $expected = '';
        $this->assertSame(
            $expected,
            $executionResult,
            'Variable ( executionResult ) doesn\'t have the expected value.'
        );
    }
}
